### ISSUE TITLE
Erro quando não há dados disponíveis para o ano atual

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/orcamento.inesc.org.br#84]
Quando acessando o "index", sem especificar um ano, ele escolhe automaticamente o ano atual:
https://github.com/okfn-brasil/orcamento.inesc.org.br/blob/cc32f3d536288f15e90765c5afd53558fcc33493/app/assets/javascripts/angular_app/controllers/app_controller.js.coffee#L7
Porém, aparentemente ele não está verificando se o ano atual possui dados a serem exibidos, o que geral um problema quando esses dados não estão disponíveis, por exemplo, no começo de um novo ano.

**Comment by vitorbaptista** [comment]
Resolvido. Agora ele, por padrão, pega o último ano que tem dados disponíveis.
