### ISSUE TITLE
Barras por ano desordenadas no Chrome

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/orcamento.inesc.org.br#85]
A Ana me mandou esse screen:
http://srv3.inesc.org.br/orcamento/desordenadas.png
(as barrinhas verdes estão desordenadas)
Testei no Chromium (Versão 40.0.2214.111 (64-bit)) aqui no Linux e tive o mesmo problema.
Está dando esse erro no console do Chromium:

    Uncaught TypeError: Cannot read property 'webkit' of undefined
    application-db873a685d9ca42d62adc7bb7a03a5db.js:22

No Firefox aqui está normal.

No Epiphany está errado. Logo deve algo relacionado ao WebKit...

**Comment by vitorbaptista** [comment]
@andresmrm O problema era bem mais simples: estava ordenando os anos mas eles eram strings ao invés de números, então a ordenação saía errada.

Esse erro do webkit é relacionado ao OpenSpendingJS. Ele usa um JQuery mais antigo, que tinha o $.browser.webkit, mas foi deprecated já há um bom tempo e no JQuery do Orçamento ele não existe mais. É ruim ter essa exception mas é algo que pode ser ignorado.
